---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pr
  name: amiserv
spec:
  selector:
    matchLabels:
      run: amiserv
  replicas: 1
  template:
    metadata:
      labels:
        run: amiserv
    spec:
      containers:
        - name: amiserv
          image: registry.carakan.id/belajar/sudobash/amiserv:v0.1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: registry-carakan
---
apiVersion: v1
kind: Service
metadata:
  namespace: pr
  name: amiserv-service
spec:
  type: NodePort
  selector:
    run: amiserv
  ports:
    - port: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-amiserv
  namespace: pr
spec:
  rules:
    - host: amiserv.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amiserv-service
                port:
                  number: 80
  ingressClassName: nginx